{
  "name": "yukibot-md",
  "version": "1.8.2",
  "description": "WhatsApp Bot Multi Device",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "start": "node index.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/The-King-Destroy/YukiBot-MD.git"
  },
  "author": "The-King-Destroy",
  "license": "MIT",
  "dependencies": {
    "@hapi/boom": "^10.0.1",
    "@vitalets/google-translate-api": "^8.0.0",
    "@whiskeysockets/baileys": "github:WhiskeySockets/Baileys",
    "acrcloud": "^1.4.0",
    "aptoide-scraper": "github:DIEGO-OFC/dv-aptoide-scraper",
    "awesome-phonenumber": "^3.4.0",
    "axios": "^1.1.2",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.20.2",
    "cfonts": "^3.3.0",
    "chalk": "^5.3.0",
    "cheerio": "1.0.0-rc.12",
    "cookie-parser": "^1.4.6",
    "ejs": "^3.1.10",
    "express": "^4.19.2",
    "file-type": "^18.0.0",
    "fluent-ffmpeg": "^2.1.2",
    "form-data": "^4.0.0",
    "formdata-node": "^5.0.0",
    "google-libphonenumber": "^3.2.38",
    "human-readable": "^0.2.1",
    "jimp": "^0.16.13",
    "lodash": "^4.17.21",
    "lowdb": "^3.0.0",
    "megajs": "^1.1.3",
    "mime-types": "^2.1.35",
    "moment-timezone": "^0.5.45",
    "multer": "^1.4.5-lts.1",
    "node-cache": "^5.1.2",
    "node-fetch": "^3.3.2",
    "node-webpmux": "^3.1.7",
    "performance-now": "^2.1.0",
    "pino": "^8.21.0",
    "qrcode": "^1.5.3",
    "syntax-error": "^1.4.0",
    "terminal-image": "^2.0.0",
    "url-regex-safe": "^3.0.0",
    "wa-sticker-formatter": "^4.4.4",
    "ws": "^8.17.1",
    "yargs": "^17.7.2",
    "yt-search": "^2.10.4"
  },
  "engines": {
    "node": ">=20.0.0"
  }
}